[replay]
type = "NanoChart"
[gameplay]
skipIntro = "space"
videobga = false
invertPlaySpeed = "f2"
imagebga = true
pause = "escape"
increasePlaySpeed = "f4"
invertTimeRate = "f7"
inputOffset = 0
needTimeRound = true
decreaseTimeRate = "f5"
increaseTimeRate = "f6"
quickRestart = "`"
timeToPrepare = 2
decreasePlaySpeed = "f3"
[screenshot]
capture = "f12"
open = "lshift"
[screen]
browser = "tab"
settings = "f1"
[dim]
result = 0.75
gameplay = 0.75
select = 0.5
[select]
adjustDifficulty = "f3"
adjustDifficultyAccuracy = 26
selectRandomNoteChartSet = "f2"
adjustDifficultyPerformance = 300
[online]
host = "https://soundsphere.xyz"
quick_login_key = ""
session = ""
email = ""
token = ""
userId = 1
[audio]
primaryAudioMode = "streamMemoryTempo"
previewAudioMode = "streamOpenAL"
secondaryAudioMode = "sample"
[volume]
music = 1
global = 1
effects = 1
[general]
noteskin10key2scratch = "userdata/skins/soundsphere circle/10key2scratch.toml"
fps = 240
theme = "userdata/themes/new"
noteskin5key = "userdata/skins/soundsphere circle/5key.toml"
noteskin4key = "userdata/skins/soundsphere arrow/noteskin4key_test.json"
speed = 1
[parser]
midiConstantVolume = false